# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # 사용할 버전, 최신 버전으로 설정 가능
    hooks:
      - id: trailing-whitespace  # 불필요한 공백 제거
      - id: end-of-file-fixer  # 파일의 끝이 개행 문자로 끝나도록 수정
      - id: check-yaml  # YAML 파일 형식 검사
      - id: check-json  # JSON 파일 형식 검사
      - id: check-added-large-files  # 커밋에 큰 파일이 포함되었는지 확인
      - id: pretty-format-json  # JSON 파일을 정리된 형식으로 자동 수정
        args: ["--no-sort-keys"]  # JSON 키 순서를 유지하도록 설정

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Black 포매터 버전
    hooks:
      - id: black  # Python 코드 스타일을 자동으로 정리

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Flake8 버전
    hooks:
      - id: flake8  # Python 코드 린터, 코드 스타일 검사
        args: ["--max-line-length=88"]  # 최대 라인 길이를 설정 (Black과 일치)
